PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE DATA(
ID INT PRIMARY KEY NOT NULL,
userName TEXT NOT NULL,
password INT NOT NULL
);
INSERT INTO DATA VALUES(1,'User1',12345678);
INSERT INTO DATA VALUES(2,'User2',12345);
COMMIT;
